networks:
  spotify-network:
    name: spotify-network
    driver: bridge

services:
  spotify-backoffice:
    container_name: spotify-backoffice
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: spotify-backoffice:latest
    command: sh -c "npm install && npm run dev"
    networks:
      - spotify-network
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
