networks:
  spotify-network:
    name: spotify-network
    driver: bridge

services:
  spotify-clone:
    container_name: spotify-clone
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: spotify-clone:latest
    networks:
      - spotify-network
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
