volumes:
  spotify-db-volume:
    name: spotify-db-volume

services:
  spotify-db:
    image: postgres:17.5
    container_name: spotify-db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - spotify-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
